platform :ios, '11.0'
use_frameworks!

target 'App' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorDataStorageSqlite', :path => '/Users/queaujeanpierre/Documents/ProjectswithCapacitor/publishProjects/vuejs-capacitor-apps/new/vue-capacitor-data-storage-sqlite/node_modules/capacitor-data-storage-sqlite'
  # Do not delete
end
